ARDUINO_DIR = /usr/lib/arduino-1.8.4
ARDMK_DIR = ~/code/arduino/Arduino-Makefile
AVRDUDE = /usr/bin/avrdude
AVR_TOOLS_DIR = /usr/lib/arduino-1.8.4/hardware/tools/avr
BOARD_TAG     = "micro"
MONITOR_PORT = /dev/ttyACM1
include ~/code/arduino/Arduino-Makefile/Arduino.mk
