# Arduino Make file. Refer to https://github.com/sudar/Arduino-Makefile
ARDUINO_DIR = /usr/lib/arduino-1.8.4
ARDMK_DIR = Arduino-Makefile
AVRDUDE = /usr/bin/avrdude
AVR_TOOLS_DIR = /usr/lib/arduino-1.8.4/hardware/tools/avr
BOARD_TAG    = uno
AVRDUDE_OPTS = -v
USER_LIB_PATH = ../libs
ARDUINO_LIBS = RFReceiver PinChangeInterruptHandler RFTransmitter
include ${ARDMK_DIR}/Arduino.mk
