#!/usr/bin/python3
# Copyright 2018 Alexander Wilhelmi
# This file is part of 433control.
# 
# 433control is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# 433control is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with 433control.  If not, see <http://www.gnu.org/licenses/>.
# 

SERIAL_WAIT_READY=1.8
SERIAL_BAUDRATE=500000
RF_NODES_ENV_KEY = 'RF_NODES'
NODES_LIST_FILE = '/etc/nodelist'



#
# argument parsing
#
from os.path import exists
from sys import exit,argv
fname=None
quiet=False
only_local=False
verbose=False

nr_consumed=0
for i in argv:
    if i=='-l':
        print("controlable things:")
        print()
        print("11 : light")
        print("12 : room ventilation fan")
        print("13 : led strip")
        print("14 : intense light")
        print()
        print("21 : dusteater")
        print("22 : ?")
        print("23 : ?")
        print("24 : air conditioner")
        print()
        exit(0)
    elif i[:2]=='-f':
        j=argv.index("-f")
        if len(argv[j]) > 1:
            fname=argv[j+1]
            nr_consumed+=2
        else:
            fname=i[2:]
            nr_consumed+=1
    elif i=='-q':
        nr_consumed+=1
        quiet=True
        verbose=False
    elif i=='-v':
        nr_consumed+=1
        quiet=False
        verbose=True
    elif i=='-L':
        nr_consumed+=1
        only_local=True

#
# check local/remote
# and in case of remote stop here
# and call this program on the remote node
#
if verbose:    
    from socket import gethostname

if exists ('/etc/has433rf'):
    if verbose:
        print(f'{gethostname()} has rf')
    pass
elif only_local:
    if verbose:
        print(f'{gethostname()} has no rf')
    exit(1)
else: # call remote
    if verbose:
        print(f'{gethostname()} has no rf , calls remote ...')
    from subprocess import call
    from sys import argv
    from os import environ
    
    # fix annoying warning
    if 'LD_PRELOAD' in environ.keys():
        from re import sub
        environ['LD_PRELOAD'] = sub("[^ ]+libswmhack[^ ]+","",environ['LD_PRELOAD'])
    if RF_NODES_ENV_KEY in environ.keys():
        rf_nodes = environ[RF_NODES_ENV_KEY].split(' ')
    else:
        with open(NODES_LIST_FILE) as nlf:
            if not verbose:
                from socket import gethostname
            rf_nodes = [node.strip() for node in nlf.read().split('\n')]
            rf_nodes.remove(gethostname())
            while '' in rf_nodes:
                rf_nodes.remove('')
            #rf_nodes.reverse()
    if verbose:
        print(f"rf_nodes are {rf_nodes}")
    node_index = 0
    try:
        while not call(["ssh",rf_nodes[node_index] , argv[0], '-L' ] + (argv[1:] if len(argv) > 0 else [])) == 0 :
            node_index+=1
    except IndexError:
        from sys import stderr
        print(f"node index = {node_index}",file=stderr)
        raise
    from sys import exit
    exit(0)



intbytes=2
maxintsize=2**(intbytes*8)
byteorder="little"
port='/dev/ttyACM0'
codedir="/usr/share/433control"
codes={    "1_1_0"   :    "remote1_btn1_off"    ,
           "1_1_1"   :    "remote1_btn1_on"     ,
           "1_2_0"   :    "remote1_btn2_off"    ,
           "1_2_1"   :    "remote1_btn2_on"     ,
           "1_3_0"   :    "remote1_btn3_off"    ,
           "1_3_1"   :    "remote1_btn3_on"     ,
           "1_4_0"   :    "remote1_btn4_off"    ,
           "1_4_1"   :    "remote1_btn4_on"     ,
           "1_a_0"   :    "remote1_btnall_off"  ,
           "1_a_1"   :    "remote1_btnall_on"   ,  
           "2_1_0"   :    "remote2_btn1_off"    ,
           "2_1_1"   :    "remote2_btn1_on"     ,
           "2_2_0"   :    "remote2_btn2_off"    ,
           "2_2_1"   :    "remote2_btn2_on"     ,
           "2_3_0"   :    "remote2_btn3_off"    ,
           "2_3_1"   :    "remote2_btn3_on"     ,
           "2_4_0"   :    "remote2_btn4_off"    ,
           "2_4_1"   :    "remote2_btn4_on"     ,
           "2_a_0"   :    "remote2_btnall_off"  ,
           "2_a_1"   :    "remote2_btnall_on"   ,
           "3_1_1"   :    "remote3_btn1_on"     ,   
           "3_1_0"   :    "remote3_btn1_off"    ,   
           "3_2_1"   :    "remote3_btn2_on"     ,   
           "3_2_0"   :    "remote3_btn2_off"    ,   
           "3_3_1"   :    "remote3_btn3_on"     ,   
           "3_3_0"   :    "remote3_btn3_off"    ,   
           "3_4_1"   :    "remote3_btn4_on"     ,   
           "3_4_0"   :    "remote3_btn4_off"    ,   
           "4_1_1"   :    "remote4_btn1_on"    ,   
           "4_1_0"   :    "remote4_btn1_off"    ,   
           "4_2_1"   :    "remote4_btn2_on"    ,   
           "4_2_0"   :    "remote4_btn2_off"    ,   
           "4_3_1"   :    "remote4_btn3_on"    ,   
           "4_3_0"   :    "remote4_btn3_off"    ,   

        }

def decode_args(argv,nr_consumed):
    args = argv[nr_consumed+1]
    for i in range(nr_consumed+2,len(argv)):
        args = args + argv[i]
        args = args.strip()
        args = args.replace(" ","")
    if len(args) == 3:
        return args
    else:
        if not verbose:
            global gethostname
            from socket import gethostname
        from sys import stderr
        print(f"node {gethostname()} did not understand args:\nargv={argv}\nnr_consumed={nr_consumed}",file=stderr)
        raise Exception("did not understand args")


import serial
s = serial.Serial(port=port, baudrate=SERIAL_BAUDRATE,timeout=0)

from time import sleep
if not quiet:
    print("waiting "+str(SERIAL_WAIT_READY)+" sec for the serial to get ready... ",end="")
sleep(1.8)
if verbose:
    print("done")
txt=s.read_all().decode(errors="replace").strip()
if len(txt)>0:
    print(txt)


if fname is None:
    args = decode_args(argv,nr_consumed)
    fname=codedir+'/'+codes[args[0]+'_'+args[1]+'_'+args[2]]

##print("code = "+fname.split("/")[-1])
f=open(fname,'rt')
data=f.read().strip()
f.close()
liste=data.split(" ")
liste=[0x0000,0x0000,0x0000,0xFFFF]+liste
liste.append(0)
#print("length: "+ str(len(liste)))
#print(liste)
for i in liste:
    a=int(i)
    if a > maxintsize - 1:
            raise Exception("value to large")
    z=a.to_bytes(intbytes,byteorder,signed=False)
    z0=z[0].to_bytes(1,byteorder,signed=False)
    z1=z[1].to_bytes(1,byteorder,signed=False)
    s.write(z1)
    s.write(z0)
    s.flush()

txt=s.read_all().decode(errors="replace").strip()
if len(txt)>0:
    print(txt)

s.close()
