ARDUINO_DIR = /usr/lib/arduino-1.8.4
ARDMK_DIR = ~/code/arduino/Arduino-Makefile
AVRDUDE = /usr/bin/avrdude
AVR_TOOLS_DIR = /usr/lib/arduino-1.8.4/hardware/tools/avr
#MCU = atmega169
BOARD_TAG     = uno
#ISP_PROG   = stk500v1
#ISP_PORT   = /dev/ttyACM0
AVRDUDE_OPTS= -v
#AVRDUDE_ISP_BAUDRATE = 19200
include ~/code/arduino/Arduino-Makefile/Arduino.mk
